In [1]:
from src.utils import (
    load_config,
    load_data,
    split_input_output,
    split_train_test,
    serialize_data,
    deserialize_data
)

In [2]:
config = load_config()

In [3]:
config

{'directories': {'raw': 'data/raw',
  'interim': 'data/interim',
  'processed': 'data/processed'},
 'files': {'dataset_name': 'credit_risk_dataset.csv',
  'interim': {'X_train': 'X_train.pkl',
   'y_train': 'y_train.pkl',
   'X_valid': 'X_valid.pkl',
   'y_valid': 'y_valid.pkl',
   'X_test': 'X_test.pkl',
   'y_test': 'y_test.pkl'}},
 'path_raw_dir': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/raw',
 'path_interim_dir': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim',
 'path_processed_dir': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/processed',
 'path_raw_data': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/raw/credit_risk_dataset.csv',
 'path_X_train': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_train.pkl',
 'path_y_train': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_train.pkl',
 'path_X_valid': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_valid.pkl',
 'path_y_valid': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_valid.pkl',
 'path_X_test': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_test.pkl',
 'path_y_test': '/home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_test.pkl'}

In [4]:
FNAME = config["path_raw_data"]
data = load_data(FNAME)

Data Shape: (32581, 12)

In [5]:
data["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [6]:
TARGET_COL = "loan_status"
X, y = split_input_output(data, TARGET_COL)

Original data shape: (32581, 12)
X data shape       : (32581, 11)
y data shape       : (32581,)

In [7]:
X.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,0.55,Y,4

In [8]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: loan_status, dtype: int64

In [9]:
X_train, X_non_train, y_train, y_non_train = split_train_test(
    X, y,
    test_size=0.2,
    random_state=42
)

X_valid, X_test, y_valid, y_test = split_train_test(
    X=X_non_train,
    y=y_non_train,
    test_size=0.5,
    random_state=42
)

X train shape: (26064, 11)
X test shape : (6517, 11)
y train shape: (26064,)
y test shape : (6517,)
X train shape: (3258, 11)
X test shape : (3259, 11)
y train shape: (3258,)
y test shape : (3259,)

In [10]:
serialize_data(X_train, config["path_X_train"])
serialize_data(X_valid, config["path_X_valid"])
serialize_data(X_test, config["path_X_test"])
serialize_data(y_train, config["path_y_train"])
serialize_data(y_valid, config["path_y_valid"])
serialize_data(y_test, config["path_y_test"])

Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_train.pkl
Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_valid.pkl
Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_test.pkl
Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_train.pkl
Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_valid.pkl
Sukses menyimpan data ke: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_test.pkl

In [11]:
X_coba = deserialize_data(path=config["path_X_train"])

In [12]:
X_coba.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
15884,25,241875,MORTGAGE,4.0,EDUCATION,A,16000,7.05,0.07,N,4
15138,21,18000,RENT,5.0,PERSONAL,B,1500,12.18,0.08,N,4
7474,25,53000,MORTGAGE,10.0,MEDICAL,B,16000,12.53,0.30,N,2
18212,28,16800,OWN,NaN,MEDICAL,C,5000,13.98,0.30,N,8
6493,25,50000,MORTGAGE,2.0,VENTURE,A,10000,7.90,0.20,N,2